export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES';
export const GET_ALL_ARTICLES_FAILED = 'GET_ALL_ARTICLES_FAILED';
export const GET_ALL_ARTICLES_SUCCESS = 'GET_ALL_ARTICLES_SUCCESS';
export const SEARCH_VALUE = 'SEARCH_VALUE';
